version: '3.3'
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ~/nginx-proxy-manager/docker/volumes/nginx-proxy-manager/data:/data
      - ~/nginx-proxy-manager/docker/volumes/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
