apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-go-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: backend-go
  template:
    metadata:
      labels:
        app: backend-go
    spec:
      serviceAccountName: go-dashboard-sa
      containers:
      - name: backend-go
        image: aakkiiff/k8s-dashbe:0.0.3
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: backend-go-clusterip
  namespace: default
spec:
  selector:
    app: backend-go
  ports:
  - port: 8080
    targetPort: 8080