apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-go-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend-go
  template:
    metadata:
      labels:
        app: frontend-go
    spec:
      serviceAccountName: go-dashboard-sa
      containers:
      - name: frontend-go
        image: aakkiiff/k8s-dashfe:0.0.3
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-go-clusterip
  namespace: default
spec:
  selector:
    app: frontend-go
  ports:
  - port: 3000
    targetPort: 3000