apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-dashboard-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-dashboard-cr
rules:
- apiGroups: ["*"]  
  resources: ["*"]   
  verbs: ["*"]      

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: go-dashboard-crb
subjects:
- kind: ServiceAccount
  name: go-dashboard-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: go-dashboard-cr
  apiGroup: rbac.authorization.k8s.io
