global:
  scrape_interval: 2s
scrape_configs:
 - job_name: Prometheus
   static_configs:
    - targets:
       - prometheus:9090

 - job_name: Node_Exporter
   static_configs:
    - targets:
       - nodeexporter:9100
